//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cesapi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int Id { get; set; }
        public int ORGID { get; set; }
        public string NAME { get; set; }
        public string LINE1 { get; set; }
        public string LINE2 { get; set; }
        public string LINE3 { get; set; }
        public string CITY { get; set; }
        public string POSTCODE { get; set; }
        public bool MAINSITE { get; set; }
    
        public virtual Organisation Organisation { get; set; }
    }
}
