//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cesapi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organisation()
        {
            this.Locations = new HashSet<Location>();
            this.QuestionnaireResults = new HashSet<QuestionnaireResult>();
        }
    
        public int Id { get; set; }
        public string NAME { get; set; }
        public string SECTOR { get; set; }
        public int EMPLOYEES { get; set; }
        public int CONTACTID { get; set; }
        public Nullable<int> INVOICEID { get; set; }
        public string WEBADDRESS { get; set; }
        public bool INCLUDEREGISTER { get; set; }
        public bool INCLUDEMARKETING { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location> Locations { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionnaireResult> QuestionnaireResults { get; set; }
    }
}
