//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cesmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireResult
    {
        public int id { get; set; }
        public int organisation { get; set; }
        public string C2_1 { get; set; }
        public string C2_2 { get; set; }
        public Nullable<bool> C2_3 { get; set; }
        public string C3_1 { get; set; }
        public Nullable<bool> C3_2 { get; set; }
        public Nullable<bool> C3_3 { get; set; }
        public string C3_4 { get; set; }
        public Nullable<bool> C3_5 { get; set; }
        public Nullable<bool> C3_6 { get; set; }
        public Nullable<bool> C3_7 { get; set; }
        public Nullable<bool> C4_1 { get; set; }
        public Nullable<bool> C4_2 { get; set; }
        public Nullable<bool> C4_3 { get; set; }
        public Nullable<bool> C4_4 { get; set; }
        public string C4_5 { get; set; }
        public string C4_6 { get; set; }
        public Nullable<bool> C5_1 { get; set; }
        public Nullable<bool> C5_2 { get; set; }
        public Nullable<bool> C5_3 { get; set; }
        public Nullable<bool> C5_4 { get; set; }
        public string C5_5 { get; set; }
        public Nullable<bool> C5_6 { get; set; }
        public Nullable<bool> C5_7 { get; set; }
        public Nullable<bool> C6_1 { get; set; }
        public string C6_1_1 { get; set; }
        public Nullable<bool> C6_1_2 { get; set; }
        public Nullable<bool> C6_1_3 { get; set; }
        public Nullable<bool> C6_1_4 { get; set; }
        public Nullable<bool> C6_2 { get; set; }
        public Nullable<bool> C6_2_1 { get; set; }
        public Nullable<bool> C6_2_2 { get; set; }
        public Nullable<bool> C6_2_3 { get; set; }
        public Nullable<bool> C6_2_4 { get; set; }
        public Nullable<bool> C6_3 { get; set; }
        public Nullable<bool> C7_1 { get; set; }
        public Nullable<bool> C7_2 { get; set; }
        public Nullable<bool> C7_3 { get; set; }
    
        public virtual Organisation Organisation1 { get; set; }
    }
}
